### ISSUE TITLE
fast-jsonapi support?

### ISSUE THREAD

**Issue by silasb** [superiorlu/jsonapi-swagger#7]
We use fast-jsonapi Gem and wonder if we can generate swagger docs from fast-jsonapi? If not, do you have an idea of what it'd take to do it?

**Comment by superiorlu** [comment]
It ’s not supported yet, but I will  look into fast-jsonapi, it is already in my schedule. Thank your issue.

**Comment by superiorlu** [comment]
@silasb support fast-jsonapi at 0.8.0, you can upgrade this version.
